# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: "Engin Yöyen"
description: > # this means to ignore newlines until "email:"
   Software Engineer

email: mail@enginyoyen.com
logo: "/assets/article_images/wp-content/uploads/2015/01/Screen-Shot-2015-01-05-at-00.19.29-300x300.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Engin Yöyen'
author: 'Engin Yöyen'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://enginyoyen.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-49028885-2

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/enginyoyen
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/enginyoyen
    desc:	Linkedin profile
    share_url:
    share_title:
    share_link:
